version: 2.1
jobs:
  build:
    working_directory: ~/fomo-packages-public
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    environment:
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - run:
          name: test
          command: npm run test
      - run:
          name: bump version
          command: npm run update-version
      - run:
          name: check-packages
          command: npm run check-packages
      - run:
          name: publish
          command: npm run publish-packages
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
